### GET ALL PRODUCTS
GET http://localhost:3333/api/v1/products
### GET PRODUCTS BY ID
GET http://localhost:3333/api/v1/products/21f01366-205c-458d-8276-e4feaf59ef8c
### POST PRODUCTS
POST http://localhost:3333/api/v1/products
Content-Type: application/json

{
    "name": "Andreyna Carvalho",
    "price": 12,
    "quantity": 5
}
### EDIT PRODUCT
PUT http://localhost:3333/api/v1/products/21f01366-205c-458d-8276-e4feaf59ef8c
Content-Type: application/json

{
    "name": "Drica",
    "price": 12,
    "quantity": 5
}
### DELETE PRODUCT
DELETE http://localhost:3333/api/v1/products/21f01366-205c-458d-8276-e4feaf59ef8c
###

### GET ALL USER
GET http://localhost:3333/api/v1/users
### GET USER BY ID
GET http://localhost:3333/api/v1/users/a8a67d13-d0c9-409d-8fc8-e32018ad96f4
### POST USER
POST http://localhost:3333/api/v1/users
Content-Type: application/json

{
    "name": "Andreyna Carvalho",
    "email": "andreyna.m.carvalho@gmail.com",
    "password": "12345678"
}
### EDIT USER
PUT http://localhost:3333/api/v1/users/a8a67d13-d0c9-409d-8fc8-e32018ad96f4
Content-Type: application/json

{
    "name": "Drica",
    "email": "andreyna.m.carvalho@gmail.com",
    "password": "12345678"
}
### DELETE USER
DELETE http://localhost:3333/api/v1/users/a8a67d13-d0c9-409d-8fc8-e32018ad96f4
###
