### GET ALL PRODUCTS
GET http://localhost:3333/api/v1/products
### GET PRODUCTS BY ID
GET http://localhost:3333/api/v1/products/21f01366-205c-458d-8276-e4feaf59ef8c
### POST PRODUCTS
POST http://localhost:3333/api/v1/products
Content-Type: application/json

{
    "name": "Andreyna Carvalho",
    "price": 12,
    "quantity": 5
}
### EDIT PRODUCT
PUT http://localhost:3333/api/v1/products/21f01366-205c-458d-8276-e4feaf59ef8c
Content-Type: application/json

{
    "name": "Drica",
    "price": 12,
    "quantity": 5
}
### DELETE PRODUCT
DELETE http://localhost:3333/api/v1/products/21f01366-205c-458d-8276-e4feaf59ef8c
###

### GET ALL USER, NECESSARY TOKEN
GET http://localhost:3333/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTg2MjE3NjIsImV4cCI6MTY1ODcwODE2Miwic3ViIjoiOTFkOGNkZDEtZjE2OC00NTI1LTg5MDctYTQ4MzFiMDI3ODI1In0.GSIgtB0evQ_Jw81CDrKN4LobUfGHfydJlr62Z5RmG2w
### GET USER BY ID
GET http://localhost:3333/api/v1/users/a8a67d13-d0c9-409d-8fc8-e32018ad96f4
### POST USER
POST http://localhost:3333/api/v1/users
Content-Type: application/json

{
    "name": "Drica",
    "email": "drica@gmail.com",
    "password": "12345678"
}
### EDIT USER
PUT http://localhost:3333/api/v1/users/a8a67d13-d0c9-409d-8fc8-e32018ad96f4
Content-Type: application/json

{
    "name": "Drica",
    "email": "andreyna.m.carvalho@gmail.com",
    "password": "12345678"
}
### DELETE USER
DELETE http://localhost:3333/api/v1/users/a8a67d13-d0c9-409d-8fc8-e32018ad96f4
###

### Create Session
POST http://localhost:3333/api/v1/sessions
Content-Type: application/json

{
    "email": "drica@gmail.com",
    "password": "12345678"
}
###
